version: '3'

vars:
  IMAGE: 'qemubox-sandbox'
  TAG: 'dev'

tasks:
  default:
    desc: Build the sandbox image
    cmds:
      - task: build

  build:
    desc: Build the Docker image locally
    cmds:
      - docker build --platform linux/amd64 -t {{.IMAGE}}:{{.TAG}} .

  run:
    desc: Run the image locally for testing
    cmds:
      - |
        docker run -d --rm --name sandbox-test \
          --privileged \
          -v /sys/fs/cgroup:/sys/fs/cgroup:rw \
          -p 2222:22 \
          {{.IMAGE}}:{{.TAG}}
        echo "Container started. SSH available on localhost:2222"
        echo "To stop: task stop"

  stop:
    desc: Stop the test container
    cmds:
      - docker stop sandbox-test || true

  logs:
    desc: View container logs
    cmds:
      - docker logs -f sandbox-test

  shell:
    desc: Open a shell in the test container
    cmds:
      - docker exec -it sandbox-test /bin/bash

  clean:
    desc: Remove built image
    cmds:
      - docker rmi {{.IMAGE}}:{{.TAG}} || true
