// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.1
// source: github.com/spin-stack/spinbox/api/services/stdio/v1/stdio.proto

package stdio

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WriteStdinRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// container_id identifies the container.
	ContainerID string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// exec_id identifies the exec process (empty string for init process).
	ExecID string `protobuf:"bytes,2,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	// data is the bytes to write to stdin.
	Data          []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteStdinRequest) Reset() {
	*x = WriteStdinRequest{}
	mi := &file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteStdinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteStdinRequest) ProtoMessage() {}

func (x *WriteStdinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteStdinRequest.ProtoReflect.Descriptor instead.
func (*WriteStdinRequest) Descriptor() ([]byte, []int) {
	return file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_rawDescGZIP(), []int{0}
}

func (x *WriteStdinRequest) GetContainerID() string {
	if x != nil {
		return x.ContainerID
	}
	return ""
}

func (x *WriteStdinRequest) GetExecID() string {
	if x != nil {
		return x.ExecID
	}
	return ""
}

func (x *WriteStdinRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteStdinResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// bytes_written is the number of bytes actually written.
	BytesWritten  uint32 `protobuf:"varint,1,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteStdinResponse) Reset() {
	*x = WriteStdinResponse{}
	mi := &file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteStdinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteStdinResponse) ProtoMessage() {}

func (x *WriteStdinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteStdinResponse.ProtoReflect.Descriptor instead.
func (*WriteStdinResponse) Descriptor() ([]byte, []int) {
	return file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_rawDescGZIP(), []int{1}
}

func (x *WriteStdinResponse) GetBytesWritten() uint32 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

type ReadOutputRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// container_id identifies the container.
	ContainerID string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// exec_id identifies the exec process (empty string for init process).
	ExecID        string `protobuf:"bytes,2,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadOutputRequest) Reset() {
	*x = ReadOutputRequest{}
	mi := &file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadOutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadOutputRequest) ProtoMessage() {}

func (x *ReadOutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadOutputRequest.ProtoReflect.Descriptor instead.
func (*ReadOutputRequest) Descriptor() ([]byte, []int) {
	return file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_rawDescGZIP(), []int{2}
}

func (x *ReadOutputRequest) GetContainerID() string {
	if x != nil {
		return x.ContainerID
	}
	return ""
}

func (x *ReadOutputRequest) GetExecID() string {
	if x != nil {
		return x.ExecID
	}
	return ""
}

type OutputChunk struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// data is a chunk of output data.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// eof indicates end of stream (process exited or pipe closed).
	// When true, this is the final message and the stream will be closed.
	Eof           bool `protobuf:"varint,2,opt,name=eof,proto3" json:"eof,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputChunk) Reset() {
	*x = OutputChunk{}
	mi := &file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputChunk) ProtoMessage() {}

func (x *OutputChunk) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputChunk.ProtoReflect.Descriptor instead.
func (*OutputChunk) Descriptor() ([]byte, []int) {
	return file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_rawDescGZIP(), []int{3}
}

func (x *OutputChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *OutputChunk) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

type CloseStdinRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// container_id identifies the container.
	ContainerID string `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	// exec_id identifies the exec process (empty string for init process).
	ExecID        string `protobuf:"bytes,2,opt,name=exec_id,json=execId,proto3" json:"exec_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseStdinRequest) Reset() {
	*x = CloseStdinRequest{}
	mi := &file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseStdinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseStdinRequest) ProtoMessage() {}

func (x *CloseStdinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseStdinRequest.ProtoReflect.Descriptor instead.
func (*CloseStdinRequest) Descriptor() ([]byte, []int) {
	return file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_rawDescGZIP(), []int{4}
}

func (x *CloseStdinRequest) GetContainerID() string {
	if x != nil {
		return x.ContainerID
	}
	return ""
}

func (x *CloseStdinRequest) GetExecID() string {
	if x != nil {
		return x.ExecID
	}
	return ""
}

type CloseStdinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseStdinResponse) Reset() {
	*x = CloseStdinResponse{}
	mi := &file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseStdinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseStdinResponse) ProtoMessage() {}

func (x *CloseStdinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseStdinResponse.ProtoReflect.Descriptor instead.
func (*CloseStdinResponse) Descriptor() ([]byte, []int) {
	return file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_rawDescGZIP(), []int{5}
}

var File_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto protoreflect.FileDescriptor

const file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_rawDesc = "" +
	"\n" +
	"?github.com/spin-stack/spinbox/api/services/stdio/v1/stdio.proto\x12$containerd.vminitd.services.stdio.v1\"c\n" +
	"\x11WriteStdinRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x17\n" +
	"\aexec_id\x18\x02 \x01(\tR\x06execId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"9\n" +
	"\x12WriteStdinResponse\x12#\n" +
	"\rbytes_written\x18\x01 \x01(\rR\fbytesWritten\"O\n" +
	"\x11ReadOutputRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x17\n" +
	"\aexec_id\x18\x02 \x01(\tR\x06execId\"3\n" +
	"\vOutputChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x02 \x01(\bR\x03eof\"O\n" +
	"\x11CloseStdinRequest\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x17\n" +
	"\aexec_id\x18\x02 \x01(\tR\x06execId\"\x14\n" +
	"\x12CloseStdinResponse2\x81\x04\n" +
	"\x05StdIO\x12\x7f\n" +
	"\n" +
	"WriteStdin\x127.containerd.vminitd.services.stdio.v1.WriteStdinRequest\x1a8.containerd.vminitd.services.stdio.v1.WriteStdinResponse\x12z\n" +
	"\n" +
	"ReadStdout\x127.containerd.vminitd.services.stdio.v1.ReadOutputRequest\x1a1.containerd.vminitd.services.stdio.v1.OutputChunk0\x01\x12z\n" +
	"\n" +
	"ReadStderr\x127.containerd.vminitd.services.stdio.v1.ReadOutputRequest\x1a1.containerd.vminitd.services.stdio.v1.OutputChunk0\x01\x12\x7f\n" +
	"\n" +
	"CloseStdin\x127.containerd.vminitd.services.stdio.v1.CloseStdinRequest\x1a8.containerd.vminitd.services.stdio.v1.CloseStdinResponseB;Z9github.com/spin-stack/spinbox/api/services/stdio/v1;stdiob\x06proto3"

var (
	file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_rawDescOnce sync.Once
	file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_rawDescData []byte
)

func file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_rawDescGZIP() []byte {
	file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_rawDescOnce.Do(func() {
		file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_rawDesc), len(file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_rawDesc)))
	})
	return file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_rawDescData
}

var file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_goTypes = []any{
	(*WriteStdinRequest)(nil),  // 0: containerd.vminitd.services.stdio.v1.WriteStdinRequest
	(*WriteStdinResponse)(nil), // 1: containerd.vminitd.services.stdio.v1.WriteStdinResponse
	(*ReadOutputRequest)(nil),  // 2: containerd.vminitd.services.stdio.v1.ReadOutputRequest
	(*OutputChunk)(nil),        // 3: containerd.vminitd.services.stdio.v1.OutputChunk
	(*CloseStdinRequest)(nil),  // 4: containerd.vminitd.services.stdio.v1.CloseStdinRequest
	(*CloseStdinResponse)(nil), // 5: containerd.vminitd.services.stdio.v1.CloseStdinResponse
}
var file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_depIdxs = []int32{
	0, // 0: containerd.vminitd.services.stdio.v1.StdIO.WriteStdin:input_type -> containerd.vminitd.services.stdio.v1.WriteStdinRequest
	2, // 1: containerd.vminitd.services.stdio.v1.StdIO.ReadStdout:input_type -> containerd.vminitd.services.stdio.v1.ReadOutputRequest
	2, // 2: containerd.vminitd.services.stdio.v1.StdIO.ReadStderr:input_type -> containerd.vminitd.services.stdio.v1.ReadOutputRequest
	4, // 3: containerd.vminitd.services.stdio.v1.StdIO.CloseStdin:input_type -> containerd.vminitd.services.stdio.v1.CloseStdinRequest
	1, // 4: containerd.vminitd.services.stdio.v1.StdIO.WriteStdin:output_type -> containerd.vminitd.services.stdio.v1.WriteStdinResponse
	3, // 5: containerd.vminitd.services.stdio.v1.StdIO.ReadStdout:output_type -> containerd.vminitd.services.stdio.v1.OutputChunk
	3, // 6: containerd.vminitd.services.stdio.v1.StdIO.ReadStderr:output_type -> containerd.vminitd.services.stdio.v1.OutputChunk
	5, // 7: containerd.vminitd.services.stdio.v1.StdIO.CloseStdin:output_type -> containerd.vminitd.services.stdio.v1.CloseStdinResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_init() }
func file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_init() {
	if File_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_rawDesc), len(file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_goTypes,
		DependencyIndexes: file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_depIdxs,
		MessageInfos:      file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_msgTypes,
	}.Build()
	File_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto = out.File
	file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_goTypes = nil
	file_github_com_spin_stack_spinbox_api_services_stdio_v1_stdio_proto_depIdxs = nil
}
