// Code generated by protoc-gen-go-ttrpc. DO NOT EDIT.
// source: github.com/spin-stack/spinbox/api/services/stdio/v1/stdio.proto
package stdio

import (
	context "context"
	ttrpc "github.com/containerd/ttrpc"
)

type TTRPCStdIOService interface {
	WriteStdin(context.Context, *WriteStdinRequest) (*WriteStdinResponse, error)
	ReadStdout(context.Context, *ReadOutputRequest, TTRPCStdIO_ReadStdoutServer) error
	ReadStderr(context.Context, *ReadOutputRequest, TTRPCStdIO_ReadStderrServer) error
	CloseStdin(context.Context, *CloseStdinRequest) (*CloseStdinResponse, error)
}

type TTRPCStdIO_ReadStdoutServer interface {
	Send(*OutputChunk) error
	ttrpc.StreamServer
}

type ttrpcstdioReadStdoutServer struct {
	ttrpc.StreamServer
}

func (x *ttrpcstdioReadStdoutServer) Send(m *OutputChunk) error {
	return x.StreamServer.SendMsg(m)
}

type TTRPCStdIO_ReadStderrServer interface {
	Send(*OutputChunk) error
	ttrpc.StreamServer
}

type ttrpcstdioReadStderrServer struct {
	ttrpc.StreamServer
}

func (x *ttrpcstdioReadStderrServer) Send(m *OutputChunk) error {
	return x.StreamServer.SendMsg(m)
}

func RegisterTTRPCStdIOService(srv *ttrpc.Server, svc TTRPCStdIOService) {
	srv.RegisterService("containerd.vminitd.services.stdio.v1.StdIO", &ttrpc.ServiceDesc{
		Methods: map[string]ttrpc.Method{
			"WriteStdin": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req WriteStdinRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.WriteStdin(ctx, &req)
			},
			"CloseStdin": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req CloseStdinRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.CloseStdin(ctx, &req)
			},
		},
		Streams: map[string]ttrpc.Stream{
			"ReadStdout": {
				Handler: func(ctx context.Context, stream ttrpc.StreamServer) (interface{}, error) {
					m := new(ReadOutputRequest)
					if err := stream.RecvMsg(m); err != nil {
						return nil, err
					}
					return nil, svc.ReadStdout(ctx, m, &ttrpcstdioReadStdoutServer{stream})
				},
				StreamingClient: false,
				StreamingServer: true,
			},
			"ReadStderr": {
				Handler: func(ctx context.Context, stream ttrpc.StreamServer) (interface{}, error) {
					m := new(ReadOutputRequest)
					if err := stream.RecvMsg(m); err != nil {
						return nil, err
					}
					return nil, svc.ReadStderr(ctx, m, &ttrpcstdioReadStderrServer{stream})
				},
				StreamingClient: false,
				StreamingServer: true,
			},
		},
	})
}

type TTRPCStdIOClient interface {
	WriteStdin(context.Context, *WriteStdinRequest) (*WriteStdinResponse, error)
	ReadStdout(context.Context, *ReadOutputRequest) (TTRPCStdIO_ReadStdoutClient, error)
	ReadStderr(context.Context, *ReadOutputRequest) (TTRPCStdIO_ReadStderrClient, error)
	CloseStdin(context.Context, *CloseStdinRequest) (*CloseStdinResponse, error)
}

type ttrpcstdioClient struct {
	client *ttrpc.Client
}

func NewTTRPCStdIOClient(client *ttrpc.Client) TTRPCStdIOClient {
	return &ttrpcstdioClient{
		client: client,
	}
}

func (c *ttrpcstdioClient) WriteStdin(ctx context.Context, req *WriteStdinRequest) (*WriteStdinResponse, error) {
	var resp WriteStdinResponse
	if err := c.client.Call(ctx, "containerd.vminitd.services.stdio.v1.StdIO", "WriteStdin", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *ttrpcstdioClient) ReadStdout(ctx context.Context, req *ReadOutputRequest) (TTRPCStdIO_ReadStdoutClient, error) {
	stream, err := c.client.NewStream(ctx, &ttrpc.StreamDesc{
		StreamingClient: false,
		StreamingServer: true,
	}, "containerd.vminitd.services.stdio.v1.StdIO", "ReadStdout", req)
	if err != nil {
		return nil, err
	}
	x := &ttrpcstdioReadStdoutClient{stream}
	return x, nil
}

type TTRPCStdIO_ReadStdoutClient interface {
	Recv() (*OutputChunk, error)
	ttrpc.ClientStream
}

type ttrpcstdioReadStdoutClient struct {
	ttrpc.ClientStream
}

func (x *ttrpcstdioReadStdoutClient) Recv() (*OutputChunk, error) {
	m := new(OutputChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ttrpcstdioClient) ReadStderr(ctx context.Context, req *ReadOutputRequest) (TTRPCStdIO_ReadStderrClient, error) {
	stream, err := c.client.NewStream(ctx, &ttrpc.StreamDesc{
		StreamingClient: false,
		StreamingServer: true,
	}, "containerd.vminitd.services.stdio.v1.StdIO", "ReadStderr", req)
	if err != nil {
		return nil, err
	}
	x := &ttrpcstdioReadStderrClient{stream}
	return x, nil
}

type TTRPCStdIO_ReadStderrClient interface {
	Recv() (*OutputChunk, error)
	ttrpc.ClientStream
}

type ttrpcstdioReadStderrClient struct {
	ttrpc.ClientStream
}

func (x *ttrpcstdioReadStderrClient) Recv() (*OutputChunk, error) {
	m := new(OutputChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ttrpcstdioClient) CloseStdin(ctx context.Context, req *CloseStdinRequest) (*CloseStdinResponse, error) {
	var resp CloseStdinResponse
	if err := c.client.Call(ctx, "containerd.vminitd.services.stdio.v1.StdIO", "CloseStdin", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
