// Code generated by protoc-gen-go-ttrpc. DO NOT EDIT.
// source: api/services/stdio/v1/stdio.proto
package stdio

import (
	context "context"
	ttrpc "github.com/containerd/ttrpc"
)

type StdIOService interface {
	WriteStdin(context.Context, *WriteStdinRequest) (*WriteStdinResponse, error)
	ReadStdout(context.Context, *ReadOutputRequest, StdIO_ReadStdoutServer) error
	ReadStderr(context.Context, *ReadOutputRequest, StdIO_ReadStderrServer) error
	CloseStdin(context.Context, *CloseStdinRequest) (*CloseStdinResponse, error)
}

type StdIO_ReadStdoutServer interface {
	Send(*OutputChunk) error
	ttrpc.StreamServer
}

type stdioReadStdoutServer struct {
	ttrpc.StreamServer
}

func (x *stdioReadStdoutServer) Send(m *OutputChunk) error {
	return x.StreamServer.SendMsg(m)
}

type StdIO_ReadStderrServer interface {
	Send(*OutputChunk) error
	ttrpc.StreamServer
}

type stdioReadStderrServer struct {
	ttrpc.StreamServer
}

func (x *stdioReadStderrServer) Send(m *OutputChunk) error {
	return x.StreamServer.SendMsg(m)
}

func RegisterStdIOService(srv *ttrpc.Server, svc StdIOService) {
	srv.RegisterService("containerd.vminitd.services.stdio.v1.StdIO", &ttrpc.ServiceDesc{
		Methods: map[string]ttrpc.Method{
			"WriteStdin": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req WriteStdinRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.WriteStdin(ctx, &req)
			},
			"CloseStdin": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req CloseStdinRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.CloseStdin(ctx, &req)
			},
		},
		Streams: map[string]ttrpc.Stream{
			"ReadStdout": {
				Handler: func(ctx context.Context, stream ttrpc.StreamServer) (interface{}, error) {
					m := new(ReadOutputRequest)
					if err := stream.RecvMsg(m); err != nil {
						return nil, err
					}
					return nil, svc.ReadStdout(ctx, m, &stdioReadStdoutServer{stream})
				},
				StreamingClient: false,
				StreamingServer: true,
			},
			"ReadStderr": {
				Handler: func(ctx context.Context, stream ttrpc.StreamServer) (interface{}, error) {
					m := new(ReadOutputRequest)
					if err := stream.RecvMsg(m); err != nil {
						return nil, err
					}
					return nil, svc.ReadStderr(ctx, m, &stdioReadStderrServer{stream})
				},
				StreamingClient: false,
				StreamingServer: true,
			},
		},
	})
}

type StdIOClient interface {
	WriteStdin(context.Context, *WriteStdinRequest) (*WriteStdinResponse, error)
	ReadStdout(context.Context, *ReadOutputRequest) (StdIO_ReadStdoutClient, error)
	ReadStderr(context.Context, *ReadOutputRequest) (StdIO_ReadStderrClient, error)
	CloseStdin(context.Context, *CloseStdinRequest) (*CloseStdinResponse, error)
}

type stdioClient struct {
	client *ttrpc.Client
}

func NewStdIOClient(client *ttrpc.Client) StdIOClient {
	return &stdioClient{
		client: client,
	}
}

func (c *stdioClient) WriteStdin(ctx context.Context, req *WriteStdinRequest) (*WriteStdinResponse, error) {
	var resp WriteStdinResponse
	if err := c.client.Call(ctx, "containerd.vminitd.services.stdio.v1.StdIO", "WriteStdin", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *stdioClient) ReadStdout(ctx context.Context, req *ReadOutputRequest) (StdIO_ReadStdoutClient, error) {
	stream, err := c.client.NewStream(ctx, &ttrpc.StreamDesc{
		StreamingClient: false,
		StreamingServer: true,
	}, "containerd.vminitd.services.stdio.v1.StdIO", "ReadStdout", req)
	if err != nil {
		return nil, err
	}
	x := &stdioReadStdoutClient{stream}
	return x, nil
}

type StdIO_ReadStdoutClient interface {
	Recv() (*OutputChunk, error)
	ttrpc.ClientStream
}

type stdioReadStdoutClient struct {
	ttrpc.ClientStream
}

func (x *stdioReadStdoutClient) Recv() (*OutputChunk, error) {
	m := new(OutputChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *stdioClient) ReadStderr(ctx context.Context, req *ReadOutputRequest) (StdIO_ReadStderrClient, error) {
	stream, err := c.client.NewStream(ctx, &ttrpc.StreamDesc{
		StreamingClient: false,
		StreamingServer: true,
	}, "containerd.vminitd.services.stdio.v1.StdIO", "ReadStderr", req)
	if err != nil {
		return nil, err
	}
	x := &stdioReadStderrClient{stream}
	return x, nil
}

type StdIO_ReadStderrClient interface {
	Recv() (*OutputChunk, error)
	ttrpc.ClientStream
}

type stdioReadStderrClient struct {
	ttrpc.ClientStream
}

func (x *stdioReadStderrClient) Recv() (*OutputChunk, error) {
	m := new(OutputChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *stdioClient) CloseStdin(ctx context.Context, req *CloseStdinRequest) (*CloseStdinResponse, error) {
	var resp CloseStdinResponse
	if err := c.client.Call(ctx, "containerd.vminitd.services.stdio.v1.StdIO", "CloseStdin", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
