# Codecov configuration
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        # Don't fail CI on coverage changes
        informational: true
        target: auto
        threshold: 1%
    patch:
      default:
        # Don't fail CI on patch coverage
        informational: true
        target: auto
        threshold: 1%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true

ignore:
  # Ignore generated files
  - "**/*_generated.go"
  - "**/*.pb.go"
  # Ignore test files in coverage report
  - "**/*_test.go"
  # Ignore cmd entry points (minimal code)
  - "cmd/**/*"
  # Ignore integration tests
  - "integration/**/*"
  # Ignore platform-specific stubs (darwin)
  - "**/*_darwin.go"
  # Ignore API service protobuf files
  - "api/services/**/*"
