# Beacon Containerd Runtime - Task Runner
#
# Quick Start:
#   task build           # Build everything (shim, kernel, initrd)
#   task clean           # Clean build artifacts
#   task lint            # Lint code
#
# Development:
#   task shell           # Enter development shell
#   task menuconfig      # Configure kernel (requires KERNEL_VERSION and KERNEL_ARCH)
#
# Requirements:
#   - Go 1.23+
#   - Docker with buildx

version: '3'

silent: true

output: "prefixed"

vars:
  GO: go
  DOCKER: docker
  BUILDX: "{{.DOCKER}} buildx"
  MODULE_NAME:
    sh: go list -m
  ARCH:
    sh: uname -m
  OS:
    sh: uname -s

  # Build flags
  LDFLAGS: "-s -w"
  GO_BUILDTAGS: "no_grpc"
  GO_TAGS: '-tags "{{.GO_BUILDTAGS}}"'
  GO_LDFLAGS: "-ldflags '{{.LDFLAGS}}'"

  # Static build flags
  GO_STATIC_BUILDTAGS: "osusergo netgo static_build no_grpc"
  GO_STATIC_TAGS: '-tags "{{.GO_STATIC_BUILDTAGS}}"'
  GO_STATIC_LDFLAGS: "-ldflags '-extldflags \"-static\" {{.LDFLAGS}}'"

tasks:
  # ==========================================================================
  # Build Tasks
  # ==========================================================================

  build:
    desc: Build all components (shim, kernel, initrd)
    cmds:
      - |
        set -eou pipefail
        echo "🐳 Building all components..."
        {{.BUILDX}} bake
        echo "✓ Build complete"

  build:shim:
    desc: Build containerd shim binary (static, Linux x86_64)
    cmds:
      - |
        set -eou pipefail
        echo "🐳 Building containerd-shim-beaconbox-v1..."
        mkdir -p _output
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 {{.GO}} build {{.GO_STATIC_TAGS}} {{.GO_STATIC_LDFLAGS}} -o _output/containerd-shim-beaconbox-v1 ./cmd/containerd-shim-beaconbox-v1
        echo "✓ Shim built: _output/containerd-shim-beaconbox-v1 (static)"

  build:vminitd:
    desc: Build vminitd binary (static, Linux x86_64)
    cmds:
      - |
        set -eou pipefail
        echo "🐳 Building vminitd..."
        mkdir -p _output
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 {{.GO}} build {{.GO_STATIC_TAGS}} {{.GO_STATIC_LDFLAGS}} -o _output/vminitd ./cmd/vminitd
        echo "✓ vminitd built: _output/vminitd (static)"

  build:initrd:
    desc: Build initrd image
    cmds:
      - |
        set -eou pipefail
        echo "🐳 Building initrd..."
        {{.BUILDX}} bake initrd
        echo "✓ Initrd built: _output/beacon-initrd"

  build:kernel:
    desc: Build kernel
    cmds:
      - |
        set -eou pipefail
        echo "🐳 Building kernel..."
        {{.BUILDX}} bake kernel
        echo "✓ Kernel built"

  # ==========================================================================
  # Development Tasks
  # ==========================================================================

  shell:
    desc: Enter development shell
    cmds:
      - |
        set -eou pipefail
        echo "🐳 Building dev environment..."
        {{.BUILDX}} bake dev
        echo "🐳 Starting development shell..."
        {{.DOCKER}} run --rm -it --privileged \
          --name beacon-dev \
          -v ./:/go/src/{{.MODULE_NAME}} \
          -v /var/run/docker.sock:/var/run/docker.sock \
          -w /go/src/{{.MODULE_NAME}} \
          -e KERNEL_ARCH={{.ARCH}} \
          -e KERNEL_NPROC \
          beacon-dev

  menuconfig:
    desc: Configure kernel (requires KERNEL_VERSION and KERNEL_ARCH env vars)
    preconditions:
      - sh: "[ -n \"${KERNEL_VERSION:-}\" ]"
        msg: "KERNEL_VERSION environment variable must be set"
      - sh: "[ -n \"${KERNEL_ARCH:-}\" ]"
        msg: "KERNEL_ARCH environment variable must be set"
    interactive: true
    cmds:
      - |
        set -eou pipefail
        echo "🐳 Building menuconfig environment..."
        {{.BUILDX}} bake menuconfig
        echo "🐳 Starting kernel menuconfig..."
        echo "   Use arrow keys to navigate, Space to select, Enter to confirm"
        echo "   Press '/' to search for options"
        echo ""
      - |
        {{.DOCKER}} run --rm -it \
          -v ./kernel:/config \
          -w /usr/src/linux \
          -e KCONFIG_CONFIG=/config/config-${KERNEL_VERSION}-${KERNEL_ARCH} \
          -e TERM=${TERM:-xterm-256color} \
          beacon-menuconfig \
          bash -c "make ARCH=${KERNEL_ARCH} menuconfig && cp .config /config/config-${KERNEL_VERSION}-${KERNEL_ARCH}"

  # ==========================================================================
  # Validation Tasks
  # ==========================================================================

  validate:
    desc: Run all validation checks
    cmds:
      - |
        set -eou pipefail
        echo "🐳 Running validation..."
        {{.BUILDX}} bake validate
        echo "✓ Validation passed"

  lint:
    desc: Lint code
    cmds:
      - |
        set -eou pipefail
        echo "🐳 Running linters..."
        {{.BUILDX}} bake lint
        echo "✓ Linting passed"

  # ==========================================================================
  # Setup and Tool Installation
  # ==========================================================================

  setup:
    desc: Install all required development tools
    cmds:
      - |
        set -eou pipefail
        echo "🐳 Installing development tools..."

        # Install Go protobuf tools
        echo "  → Installing Go protobuf tools..."
        go install github.com/containerd/protobuild@v0.3.0
        go install github.com/containerd/protobuild/cmd/go-fix-acronym@v0.3.0
        go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28.1
        go install github.com/containerd/ttrpc/cmd/protoc-gen-go-ttrpc@v1.2.5
        echo "    ✓ Go protobuf tools installed"

        # Install protoc compiler
        echo "  → Installing protoc compiler..."
        PROTOBUF_VERSION=3.20.1
        PROTOBUF_DIR=$(mktemp -d)
        GOOS=$(go env GOOS)
        GOARCH=$(go env GOARCH)

        # Determine target platform for protoc download
        case "${GOOS}-${GOARCH}" in
          darwin-amd64)  TARGET="osx-x86_64" ;;
          darwin-arm64)  TARGET="osx-aarch_64" ;;
          linux-amd64)   TARGET="linux-x86_64" ;;
          linux-arm64)   TARGET="linux-aarch_64" ;;
          linux-386)     TARGET="linux-x86_32" ;;
          linux-ppc64le) TARGET="linux-ppcle_64" ;;
          windows-amd64) TARGET="win64" ;;
          windows-386)   TARGET="win32" ;;
          *)
            echo "    ⚠ Unsupported platform: ${GOOS}-${GOARCH}"
            echo "    Please install protoc manually from:"
            echo "    https://github.com/protocolbuffers/protobuf/releases"
            exit 1
            ;;
        esac

        # Download and install protoc
        mkdir -p bin
        curl -sL -o "${PROTOBUF_DIR}/protobuf.zip" \
          "https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOBUF_VERSION}/protoc-${PROTOBUF_VERSION}-${TARGET}.zip"
        unzip -qo "${PROTOBUF_DIR}/protobuf.zip" -d bin/
        rm -rf "${PROTOBUF_DIR}"

        # Install protobuf includes system-wide (requires sudo on most systems)
        # Try to install, and if it fails due to permissions, show instructions
        if [ -d /usr/local/include ] && [ -w /usr/local/include ]; then
          # We have write access
          cp -r bin/include/google /usr/local/include/
          mkdir -p /usr/local/include/google/rpc
          curl -sL \
            https://raw.githubusercontent.com/grpc/grpc/v1.45.2/src/proto/grpc/status/status.proto \
            -o /usr/local/include/google/rpc/status.proto
          echo "    ✓ Protobuf includes installed to /usr/local/include"
        else
          # Need sudo
          echo "    ⚠ Cannot write to /usr/local/include - sudo required"
          echo ""
          echo "    Please run the following commands to complete setup:"
          echo ""
          echo "      sudo mkdir -p /usr/local/include"
          echo "      sudo cp -r bin/include/google /usr/local/include/"
          echo "      sudo mkdir -p /usr/local/include/google/rpc"
          echo "      sudo curl -L https://raw.githubusercontent.com/grpc/grpc/v1.45.2/src/proto/grpc/status/status.proto -o /usr/local/include/google/rpc/status.proto"
          echo ""
        fi

        echo "    ✓ protoc compiler installed to bin/bin/protoc"
        echo ""
        echo "✓ Setup complete!"

  # ==========================================================================
  # Protobuf Tasks (optional)
  # ==========================================================================

  protos:
    desc: Generate protobuf files
    cmds:
      - |
        set -eou pipefail
        echo "🐳 Generating protobufs..."

        # protobuild requires GOPATH mode - ensure symlinks exist
        MODULE_PATH=$(grep '^module ' go.mod | awk '{print $2}')
        GOPATH_DIR="${HOME}/go/src/${MODULE_PATH}"

        if [ ! -d "${GOPATH_DIR}" ]; then
          echo "  → Creating GOPATH symlink for protobuild..."
          mkdir -p "$(dirname "${GOPATH_DIR}")"
          ln -sfn "$(pwd)" "${GOPATH_DIR}"
          echo "    ✓ Symlink created: ${GOPATH_DIR} -> $(pwd)"
        fi

        # Create symlink for containerd/api dependency (needed for proto imports)
        CONTAINERD_API_DIR="${HOME}/go/src/github.com/containerd/containerd/api"
        if [ ! -d "${CONTAINERD_API_DIR}" ]; then
          echo "  → Creating containerd/api symlink for proto imports..."
          CONTAINERD_API_MOD=$(go list -m -f '{{.Dir}}' github.com/containerd/containerd/api)
          mkdir -p "$(dirname "${CONTAINERD_API_DIR}")"
          ln -sfn "${CONTAINERD_API_MOD}" "${CONTAINERD_API_DIR}"
          echo "    ✓ Symlink created: ${CONTAINERD_API_DIR}"
        fi

        # Run protobuild from GOPATH location (required for correct import paths)
        cd "${GOPATH_DIR}/api" && PATH="$(pwd)/../bin/bin:${HOME}/go/bin:${PATH}" protobuild --quiet ${MODULE_PATH}/api/...

        # Fix Go acronyms in generated files
        go-fix-acronym -w -a '^Os' $(find api/ -name '*.pb.go')
        go-fix-acronym -w -a '(Id|Io|Uuid|Os)$$' $(find api/ -name '*.pb.go')

        echo "✓ Protobufs generated"

  check:protos:
    desc: Check if protobufs need regeneration
    cmds:
      - task: protos
      - |
        set -eou pipefail
        echo "🐳 Checking protobuf changes..."
        if [ -n "$(git status --short | grep '.pb.go')" ]; then
          echo "👹 Error: Protobuf files are out of date"
          echo "   Run 'task protos' to regenerate"
          exit 1
        fi
        echo "✓ Protobufs are up to date"

  # ==========================================================================
  # Cleanup Tasks
  # ==========================================================================

  clean:
    desc: Clean build artifacts
    cmds:
      - |
        set -eou pipefail
        echo "🧹 Cleaning build artifacts..."
        rm -rf _output
        echo "✓ Clean complete"

  # ==========================================================================
  # Utility Tasks
  # ==========================================================================

  verify:vendor:
    desc: Verify go.mod/go.sum are up to date
    cmds:
      - |
        set -eou pipefail
        echo "🐳 Verifying vendor files..."
        TMPDIR=$(mktemp -d)
        trap "rm -rf $TMPDIR" EXIT

        cp -R . $TMPDIR/beacon
        cd $TMPDIR/beacon
        {{.GO}} mod tidy
        {{.GO}} mod verify

        if ! diff -r go.mod go.sum {{.ROOT_DIR}}/; then
          echo "👹 Error: go.mod or go.sum are out of date"
          echo "   Run 'go mod tidy' to update"
          exit 1
        fi

        echo "✓ Vendor files are up to date"

  # ==========================================================================
  # All-in-one Tasks
  # ==========================================================================

  all:
    desc: Build and validate everything
    cmds:
      - task: build
      - task: validate
      - echo "✓ All tasks complete"

  default:
    desc: Default task (build everything)
    cmds:
      - task: build

  # ==========================================================================
  # Release Tasks
  # ==========================================================================

  release:
    desc: Create release tarball with proper directory structure
    cmds:
      - task: build
      - |
        set -eou pipefail
        echo "📦 Creating release tarball..."

        # Determine version from git tag or use "dev"
        VERSION=$(git describe --tags --always --dirty 2>/dev/null || echo "dev")
        RELEASE_NAME="beacon-${VERSION}-linux-x86_64"
        RELEASE_DIR="_output/release/${RELEASE_NAME}"

        # Clean and create release directory structure
        rm -rf _output/release
        mkdir -p "${RELEASE_DIR}/usr/share/beacon/bin"
        mkdir -p "${RELEASE_DIR}/usr/share/beacon/kernel"
        mkdir -p "${RELEASE_DIR}/usr/share/beacon/config"

        echo "📂 Copying artifacts to release structure..."

        # Copy kernel and initrd to /usr/share/beacon/kernel
        if [ -f "_output/beacon-kernel-x86_64" ]; then
          cp _output/beacon-kernel-x86_64 "${RELEASE_DIR}/usr/share/beacon/kernel/"
          echo "  ✓ beacon-kernel-x86_64"
        fi

        if [ -f "_output/beacon-initrd" ]; then
          cp _output/beacon-initrd "${RELEASE_DIR}/usr/share/beacon/kernel/"
          echo "  ✓ beacon-initrd"
        fi

        # Copy shim binary to /usr/share/beacon/bin
        if [ -f "_output/containerd-shim-beaconbox-v1" ]; then
          cp _output/containerd-shim-beaconbox-v1 "${RELEASE_DIR}/usr/share/beacon/bin/"
          echo "  ✓ containerd-shim-beaconbox-v1"
        fi

        # Download and install cloud-hypervisor
        echo "📥 Downloading cloud-hypervisor..."
        CH_VERSION="49.0"
        CH_URL="https://github.com/cloud-hypervisor/cloud-hypervisor/releases/download/v${CH_VERSION}/cloud-hypervisor-static"
        CH_REMOTE_URL="https://github.com/cloud-hypervisor/cloud-hypervisor/releases/download/v${CH_VERSION}/ch-remote-static"

        if [ ! -f "_output/cloud-hypervisor-static" ]; then
          curl -L -o "_output/cloud-hypervisor-static" "${CH_URL}"
          chmod +x "_output/cloud-hypervisor-static"
        fi

        if [ ! -f "_output/ch-remote-static" ]; then
          curl -L -o "_output/ch-remote-static" "${CH_REMOTE_URL}"
          chmod +x "_output/ch-remote-static"
        fi

        cp _output/cloud-hypervisor-static "${RELEASE_DIR}/usr/share/beacon/bin/cloud-hypervisor"
        cp _output/ch-remote-static "${RELEASE_DIR}/usr/share/beacon/bin/ch-remote"
        echo "  ✓ cloud-hypervisor v${CH_VERSION}"

        # Copy configuration files
        echo "📂 Copying configuration files..."
        cp -r release/config/* "${RELEASE_DIR}/usr/share/beacon/config/"
        echo "  ✓ config files (buildkit, containerd)"

        # Copy systemd service files to /usr/share/beacon/systemd
        echo "📂 Copying systemd services..."
        mkdir -p "${RELEASE_DIR}/usr/share/beacon/systemd"
        cp release/systemd/*.service "${RELEASE_DIR}/usr/share/beacon/systemd/"
        echo "  ✓ systemd services"

        # Copy install/uninstall scripts to tarball root (for easy access)
        echo "📂 Copying install scripts..."
        cp release/install.sh "${RELEASE_DIR}/"
        cp release/uninstall.sh "${RELEASE_DIR}/"
        chmod +x "${RELEASE_DIR}/install.sh"
        chmod +x "${RELEASE_DIR}/uninstall.sh"
        echo "  ✓ install/uninstall scripts"

        # Download and extract nerdctl
        echo "📥 Downloading nerdctl..."
        NERDCTL_VERSION="2.2.0"
        NERDCTL_URL="https://github.com/containerd/nerdctl/releases/download/v${NERDCTL_VERSION}/nerdctl-full-${NERDCTL_VERSION}-linux-amd64.tar.gz"
        NERDCTL_TARBALL="_output/nerdctl-full-${NERDCTL_VERSION}-linux-amd64.tar.gz"

        if [ ! -f "${NERDCTL_TARBALL}" ]; then
          curl -L -o "${NERDCTL_TARBALL}" "${NERDCTL_URL}"
        fi

        echo "📂 Extracting nerdctl-full components..."
        # Extract core binaries to /usr/share/beacon/bin
        tar -xzf "${NERDCTL_TARBALL}" -C "${RELEASE_DIR}/usr/share/beacon/" \
          bin/nerdctl \
          bin/containerd \
          bin/containerd-shim-runc-v2 \
          bin/ctr \
          bin/runc
        echo "  ✓ containerd, runc, ctr, nerdctl"

        # Extract buildkitd and buildctl to /usr/share/beacon/bin
        tar -xzf "${NERDCTL_TARBALL}" -C "${RELEASE_DIR}/usr/share/beacon/" bin/buildkitd bin/buildctl
        echo "  ✓ buildkit"

        # Extract CNI plugins to /usr/share/beacon/libexec/cni
        mkdir -p "${RELEASE_DIR}/usr/share/beacon/libexec/cni"
        tar -xzf "${NERDCTL_TARBALL}" -C "${RELEASE_DIR}/usr/share/beacon/libexec/cni" --strip-components=2 \
          libexec/cni/bandwidth \
          libexec/cni/bridge \
          libexec/cni/dhcp \
          libexec/cni/firewall \
          libexec/cni/host-device \
          libexec/cni/host-local \
          libexec/cni/ipvlan \
          libexec/cni/loopback \
          libexec/cni/macvlan \
          libexec/cni/portmap \
          libexec/cni/ptp \
          libexec/cni/tuning \
          libexec/cni/vlan
        echo "  ✓ CNI plugins"

        # Create tarball
        echo "🗜️  Creating tarball..."
        cd _output/release
        tar czf "${RELEASE_NAME}.tar.gz" "${RELEASE_NAME}"
        cd ../..

        echo "✓ Release created: _output/release/${RELEASE_NAME}.tar.gz"
        echo ""
        echo "Installation:"
        echo "  tar xzf ${RELEASE_NAME}.tar.gz"
        echo "  cd ${RELEASE_NAME}"
        echo "  sudo ./install.sh"
        echo ""
        echo "Uninstallation:"
        echo "  sudo ./uninstall.sh"
