// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: github.com/aledbf/qemubox/containerd/api/services/system/v1/info.proto

package system

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version       string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	KernelVersion string `protobuf:"bytes,2,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_rawDescGZIP(), []int{0}
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoResponse) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

type OfflineCPURequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CpuID uint32 `protobuf:"varint,1,opt,name=cpu_id,json=cpuId,proto3" json:"cpu_id,omitempty"`
}

func (x *OfflineCPURequest) Reset() {
	*x = OfflineCPURequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfflineCPURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineCPURequest) ProtoMessage() {}

func (x *OfflineCPURequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineCPURequest.ProtoReflect.Descriptor instead.
func (*OfflineCPURequest) Descriptor() ([]byte, []int) {
	return file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_rawDescGZIP(), []int{1}
}

func (x *OfflineCPURequest) GetCpuID() uint32 {
	if x != nil {
		return x.CpuID
	}
	return 0
}

type OnlineCPURequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CpuID uint32 `protobuf:"varint,1,opt,name=cpu_id,json=cpuId,proto3" json:"cpu_id,omitempty"`
}

func (x *OnlineCPURequest) Reset() {
	*x = OnlineCPURequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineCPURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineCPURequest) ProtoMessage() {}

func (x *OnlineCPURequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineCPURequest.ProtoReflect.Descriptor instead.
func (*OnlineCPURequest) Descriptor() ([]byte, []int) {
	return file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_rawDescGZIP(), []int{2}
}

func (x *OnlineCPURequest) GetCpuID() uint32 {
	if x != nil {
		return x.CpuID
	}
	return 0
}

type OfflineMemoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemoryID uint32 `protobuf:"varint,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
}

func (x *OfflineMemoryRequest) Reset() {
	*x = OfflineMemoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OfflineMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineMemoryRequest) ProtoMessage() {}

func (x *OfflineMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineMemoryRequest.ProtoReflect.Descriptor instead.
func (*OfflineMemoryRequest) Descriptor() ([]byte, []int) {
	return file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_rawDescGZIP(), []int{3}
}

func (x *OfflineMemoryRequest) GetMemoryID() uint32 {
	if x != nil {
		return x.MemoryID
	}
	return 0
}

type OnlineMemoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemoryID uint32 `protobuf:"varint,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
}

func (x *OnlineMemoryRequest) Reset() {
	*x = OnlineMemoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OnlineMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineMemoryRequest) ProtoMessage() {}

func (x *OnlineMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineMemoryRequest.ProtoReflect.Descriptor instead.
func (*OnlineMemoryRequest) Descriptor() ([]byte, []int) {
	return file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_rawDescGZIP(), []int{4}
}

func (x *OnlineMemoryRequest) GetMemoryID() uint32 {
	if x != nil {
		return x.MemoryID
	}
	return 0
}

var File_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto protoreflect.FileDescriptor

var file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_rawDesc = []byte{
	0x0a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x65,
	0x64, 0x62, 0x66, 0x2f, 0x71, 0x65, 0x6d, 0x75, 0x62, 0x6f, 0x78, 0x2f, 0x63, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2f, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2f, 0x76, 0x31, 0x2f, 0x69, 0x6e,
	0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x25, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x64, 0x2e, 0x76, 0x6d, 0x69, 0x6e, 0x69, 0x74, 0x64, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x76, 0x31, 0x1a,
	0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4f, 0x0a, 0x0c,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c,
	0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x2a, 0x0a,
	0x11, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x50, 0x55, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x63, 0x70, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x63, 0x70, 0x75, 0x49, 0x64, 0x22, 0x29, 0x0a, 0x10, 0x4f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x43, 0x50, 0x55, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a,
	0x06, 0x63, 0x70, 0x75, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63,
	0x70, 0x75, 0x49, 0x64, 0x22, 0x33, 0x0a, 0x14, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x4d,
	0x65, 0x6d, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x08, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x22, 0x32, 0x0a, 0x13, 0x4f, 0x6e, 0x6c,
	0x69, 0x6e, 0x65, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x08, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x49, 0x64, 0x32, 0xe5, 0x03,
	0x0a, 0x06, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x12, 0x53, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x33, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x76, 0x6d, 0x69, 0x6e, 0x69, 0x74, 0x64, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x76, 0x31,
	0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5e, 0x0a,
	0x0a, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x50, 0x55, 0x12, 0x38, 0x2e, 0x63, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x76, 0x6d, 0x69, 0x6e, 0x69, 0x74, 0x64,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d,
	0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x50, 0x55, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x5c, 0x0a,
	0x09, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x50, 0x55, 0x12, 0x37, 0x2e, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x76, 0x6d, 0x69, 0x6e, 0x69, 0x74, 0x64, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e,
	0x76, 0x31, 0x2e, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x50, 0x55, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x64, 0x0a, 0x0d, 0x4f,
	0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x3b, 0x2e, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x76, 0x6d, 0x69, 0x6e, 0x69, 0x74,
	0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x73, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x4d, 0x65, 0x6d, 0x6f,
	0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x12, 0x62, 0x0a, 0x0c, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x4d, 0x65, 0x6d, 0x6f, 0x72,
	0x79, 0x12, 0x3a, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x76,
	0x6d, 0x69, 0x6e, 0x69, 0x74, 0x64, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x6e, 0x6c, 0x69, 0x6e, 0x65,
	0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x44, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6c, 0x65, 0x64, 0x62, 0x66, 0x2f, 0x71, 0x65, 0x6d, 0x75, 0x62,
	0x6f, 0x78, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x73, 0x79, 0x73, 0x74, 0x65,
	0x6d, 0x2f, 0x76, 0x31, 0x3b, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_rawDescOnce sync.Once
	file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_rawDescData = file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_rawDesc
)

func file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_rawDescGZIP() []byte {
	file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_rawDescOnce.Do(func() {
		file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_rawDescData)
	})
	return file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_rawDescData
}

var file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_goTypes = []interface{}{
	(*InfoResponse)(nil),         // 0: containerd.vminitd.services.system.v1.InfoResponse
	(*OfflineCPURequest)(nil),    // 1: containerd.vminitd.services.system.v1.OfflineCPURequest
	(*OnlineCPURequest)(nil),     // 2: containerd.vminitd.services.system.v1.OnlineCPURequest
	(*OfflineMemoryRequest)(nil), // 3: containerd.vminitd.services.system.v1.OfflineMemoryRequest
	(*OnlineMemoryRequest)(nil),  // 4: containerd.vminitd.services.system.v1.OnlineMemoryRequest
	(*emptypb.Empty)(nil),        // 5: google.protobuf.Empty
}
var file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_depIdxs = []int32{
	5, // 0: containerd.vminitd.services.system.v1.System.Info:input_type -> google.protobuf.Empty
	1, // 1: containerd.vminitd.services.system.v1.System.OfflineCPU:input_type -> containerd.vminitd.services.system.v1.OfflineCPURequest
	2, // 2: containerd.vminitd.services.system.v1.System.OnlineCPU:input_type -> containerd.vminitd.services.system.v1.OnlineCPURequest
	3, // 3: containerd.vminitd.services.system.v1.System.OfflineMemory:input_type -> containerd.vminitd.services.system.v1.OfflineMemoryRequest
	4, // 4: containerd.vminitd.services.system.v1.System.OnlineMemory:input_type -> containerd.vminitd.services.system.v1.OnlineMemoryRequest
	0, // 5: containerd.vminitd.services.system.v1.System.Info:output_type -> containerd.vminitd.services.system.v1.InfoResponse
	5, // 6: containerd.vminitd.services.system.v1.System.OfflineCPU:output_type -> google.protobuf.Empty
	5, // 7: containerd.vminitd.services.system.v1.System.OnlineCPU:output_type -> google.protobuf.Empty
	5, // 8: containerd.vminitd.services.system.v1.System.OfflineMemory:output_type -> google.protobuf.Empty
	5, // 9: containerd.vminitd.services.system.v1.System.OnlineMemory:output_type -> google.protobuf.Empty
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_init() }
func file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_init() {
	if File_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfflineCPURequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineCPURequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OfflineMemoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OnlineMemoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_goTypes,
		DependencyIndexes: file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_depIdxs,
		MessageInfos:      file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_msgTypes,
	}.Build()
	File_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto = out.File
	file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_rawDesc = nil
	file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_goTypes = nil
	file_github_com_aledbf_qemubox_containerd_api_services_system_v1_info_proto_depIdxs = nil
}
