// Code generated by protoc-gen-go-ttrpc. DO NOT EDIT.
// source: github.com/spin-stack/spinbox/api/services/system/v1/info.proto
package system

import (
	context "context"
	ttrpc "github.com/containerd/ttrpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

type TTRPCSystemService interface {
	Info(context.Context, *emptypb.Empty) (*InfoResponse, error)
	OfflineCPU(context.Context, *OfflineCPURequest) (*emptypb.Empty, error)
	OnlineCPU(context.Context, *OnlineCPURequest) (*emptypb.Empty, error)
	OfflineMemory(context.Context, *OfflineMemoryRequest) (*emptypb.Empty, error)
	OnlineMemory(context.Context, *OnlineMemoryRequest) (*emptypb.Empty, error)
}

func RegisterTTRPCSystemService(srv *ttrpc.Server, svc TTRPCSystemService) {
	srv.RegisterService("containerd.vminitd.services.system.v1.System", &ttrpc.ServiceDesc{
		Methods: map[string]ttrpc.Method{
			"Info": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req emptypb.Empty
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.Info(ctx, &req)
			},
			"OfflineCPU": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req OfflineCPURequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.OfflineCPU(ctx, &req)
			},
			"OnlineCPU": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req OnlineCPURequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.OnlineCPU(ctx, &req)
			},
			"OfflineMemory": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req OfflineMemoryRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.OfflineMemory(ctx, &req)
			},
			"OnlineMemory": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req OnlineMemoryRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.OnlineMemory(ctx, &req)
			},
		},
	})
}

type ttrpcsystemClient struct {
	client *ttrpc.Client
}

func NewTTRPCSystemClient(client *ttrpc.Client) TTRPCSystemService {
	return &ttrpcsystemClient{
		client: client,
	}
}

func (c *ttrpcsystemClient) Info(ctx context.Context, req *emptypb.Empty) (*InfoResponse, error) {
	var resp InfoResponse
	if err := c.client.Call(ctx, "containerd.vminitd.services.system.v1.System", "Info", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *ttrpcsystemClient) OfflineCPU(ctx context.Context, req *OfflineCPURequest) (*emptypb.Empty, error) {
	var resp emptypb.Empty
	if err := c.client.Call(ctx, "containerd.vminitd.services.system.v1.System", "OfflineCPU", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *ttrpcsystemClient) OnlineCPU(ctx context.Context, req *OnlineCPURequest) (*emptypb.Empty, error) {
	var resp emptypb.Empty
	if err := c.client.Call(ctx, "containerd.vminitd.services.system.v1.System", "OnlineCPU", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *ttrpcsystemClient) OfflineMemory(ctx context.Context, req *OfflineMemoryRequest) (*emptypb.Empty, error) {
	var resp emptypb.Empty
	if err := c.client.Call(ctx, "containerd.vminitd.services.system.v1.System", "OfflineMemory", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}

func (c *ttrpcsystemClient) OnlineMemory(ctx context.Context, req *OnlineMemoryRequest) (*emptypb.Empty, error) {
	var resp emptypb.Empty
	if err := c.client.Call(ctx, "containerd.vminitd.services.system.v1.System", "OnlineMemory", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
