// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.1
// source: github.com/spin-stack/spinbox/api/services/system/v1/info.proto

package system

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// version is the spinbox vminitd version (e.g., "1.0.0").
	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	// kernel_version is the Linux kernel version running in the VM (e.g., "6.1.0").
	KernelVersion string `protobuf:"bytes,2,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_rawDescGZIP(), []int{0}
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoResponse) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

type OfflineCPURequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cpu_id is the logical CPU ID to offline (zero-indexed, e.g., 0, 1, 2).
	// This corresponds to /sys/devices/system/cpu/cpu{N}.
	CpuID         uint32 `protobuf:"varint,1,opt,name=cpu_id,json=cpuId,proto3" json:"cpu_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfflineCPURequest) Reset() {
	*x = OfflineCPURequest{}
	mi := &file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfflineCPURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineCPURequest) ProtoMessage() {}

func (x *OfflineCPURequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineCPURequest.ProtoReflect.Descriptor instead.
func (*OfflineCPURequest) Descriptor() ([]byte, []int) {
	return file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_rawDescGZIP(), []int{1}
}

func (x *OfflineCPURequest) GetCpuID() uint32 {
	if x != nil {
		return x.CpuID
	}
	return 0
}

type OnlineCPURequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cpu_id is the logical CPU ID to online (zero-indexed, e.g., 0, 1, 2).
	// This corresponds to /sys/devices/system/cpu/cpu{N}.
	CpuID         uint32 `protobuf:"varint,1,opt,name=cpu_id,json=cpuId,proto3" json:"cpu_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineCPURequest) Reset() {
	*x = OnlineCPURequest{}
	mi := &file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineCPURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineCPURequest) ProtoMessage() {}

func (x *OnlineCPURequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineCPURequest.ProtoReflect.Descriptor instead.
func (*OnlineCPURequest) Descriptor() ([]byte, []int) {
	return file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_rawDescGZIP(), []int{2}
}

func (x *OnlineCPURequest) GetCpuID() uint32 {
	if x != nil {
		return x.CpuID
	}
	return 0
}

type OfflineMemoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// memory_id is the memory block ID to offline (zero-indexed).
	// This corresponds to the QMP memory slot number.
	MemoryID      uint32 `protobuf:"varint,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OfflineMemoryRequest) Reset() {
	*x = OfflineMemoryRequest{}
	mi := &file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfflineMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfflineMemoryRequest) ProtoMessage() {}

func (x *OfflineMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfflineMemoryRequest.ProtoReflect.Descriptor instead.
func (*OfflineMemoryRequest) Descriptor() ([]byte, []int) {
	return file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_rawDescGZIP(), []int{3}
}

func (x *OfflineMemoryRequest) GetMemoryID() uint32 {
	if x != nil {
		return x.MemoryID
	}
	return 0
}

type OnlineMemoryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// memory_id is the memory block ID to online (zero-indexed).
	// This corresponds to the QMP memory slot number.
	MemoryID      uint32 `protobuf:"varint,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineMemoryRequest) Reset() {
	*x = OnlineMemoryRequest{}
	mi := &file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineMemoryRequest) ProtoMessage() {}

func (x *OnlineMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineMemoryRequest.ProtoReflect.Descriptor instead.
func (*OnlineMemoryRequest) Descriptor() ([]byte, []int) {
	return file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_rawDescGZIP(), []int{4}
}

func (x *OnlineMemoryRequest) GetMemoryID() uint32 {
	if x != nil {
		return x.MemoryID
	}
	return 0
}

var File_github_com_spin_stack_spinbox_api_services_system_v1_info_proto protoreflect.FileDescriptor

const file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_rawDesc = "" +
	"\n" +
	"?github.com/spin-stack/spinbox/api/services/system/v1/info.proto\x12%containerd.vminitd.services.system.v1\x1a\x1bgoogle/protobuf/empty.proto\"O\n" +
	"\fInfoResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12%\n" +
	"\x0ekernel_version\x18\x02 \x01(\tR\rkernelVersion\"*\n" +
	"\x11OfflineCPURequest\x12\x15\n" +
	"\x06cpu_id\x18\x01 \x01(\rR\x05cpuId\")\n" +
	"\x10OnlineCPURequest\x12\x15\n" +
	"\x06cpu_id\x18\x01 \x01(\rR\x05cpuId\"3\n" +
	"\x14OfflineMemoryRequest\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\rR\bmemoryId\"2\n" +
	"\x13OnlineMemoryRequest\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\rR\bmemoryId2\xe5\x03\n" +
	"\x06System\x12S\n" +
	"\x04Info\x12\x16.google.protobuf.Empty\x1a3.containerd.vminitd.services.system.v1.InfoResponse\x12^\n" +
	"\n" +
	"OfflineCPU\x128.containerd.vminitd.services.system.v1.OfflineCPURequest\x1a\x16.google.protobuf.Empty\x12\\\n" +
	"\tOnlineCPU\x127.containerd.vminitd.services.system.v1.OnlineCPURequest\x1a\x16.google.protobuf.Empty\x12d\n" +
	"\rOfflineMemory\x12;.containerd.vminitd.services.system.v1.OfflineMemoryRequest\x1a\x16.google.protobuf.Empty\x12b\n" +
	"\fOnlineMemory\x12:.containerd.vminitd.services.system.v1.OnlineMemoryRequest\x1a\x16.google.protobuf.EmptyB=Z;github.com/spin-stack/spinbox/api/services/system/v1;systemb\x06proto3"

var (
	file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_rawDescOnce sync.Once
	file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_rawDescData []byte
)

func file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_rawDescGZIP() []byte {
	file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_rawDescOnce.Do(func() {
		file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_rawDesc), len(file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_rawDesc)))
	})
	return file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_rawDescData
}

var file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_goTypes = []any{
	(*InfoResponse)(nil),         // 0: containerd.vminitd.services.system.v1.InfoResponse
	(*OfflineCPURequest)(nil),    // 1: containerd.vminitd.services.system.v1.OfflineCPURequest
	(*OnlineCPURequest)(nil),     // 2: containerd.vminitd.services.system.v1.OnlineCPURequest
	(*OfflineMemoryRequest)(nil), // 3: containerd.vminitd.services.system.v1.OfflineMemoryRequest
	(*OnlineMemoryRequest)(nil),  // 4: containerd.vminitd.services.system.v1.OnlineMemoryRequest
	(*emptypb.Empty)(nil),        // 5: google.protobuf.Empty
}
var file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_depIdxs = []int32{
	5, // 0: containerd.vminitd.services.system.v1.System.Info:input_type -> google.protobuf.Empty
	1, // 1: containerd.vminitd.services.system.v1.System.OfflineCPU:input_type -> containerd.vminitd.services.system.v1.OfflineCPURequest
	2, // 2: containerd.vminitd.services.system.v1.System.OnlineCPU:input_type -> containerd.vminitd.services.system.v1.OnlineCPURequest
	3, // 3: containerd.vminitd.services.system.v1.System.OfflineMemory:input_type -> containerd.vminitd.services.system.v1.OfflineMemoryRequest
	4, // 4: containerd.vminitd.services.system.v1.System.OnlineMemory:input_type -> containerd.vminitd.services.system.v1.OnlineMemoryRequest
	0, // 5: containerd.vminitd.services.system.v1.System.Info:output_type -> containerd.vminitd.services.system.v1.InfoResponse
	5, // 6: containerd.vminitd.services.system.v1.System.OfflineCPU:output_type -> google.protobuf.Empty
	5, // 7: containerd.vminitd.services.system.v1.System.OnlineCPU:output_type -> google.protobuf.Empty
	5, // 8: containerd.vminitd.services.system.v1.System.OfflineMemory:output_type -> google.protobuf.Empty
	5, // 9: containerd.vminitd.services.system.v1.System.OnlineMemory:output_type -> google.protobuf.Empty
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_init() }
func file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_init() {
	if File_github_com_spin_stack_spinbox_api_services_system_v1_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_rawDesc), len(file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_goTypes,
		DependencyIndexes: file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_depIdxs,
		MessageInfos:      file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_msgTypes,
	}.Build()
	File_github_com_spin_stack_spinbox_api_services_system_v1_info_proto = out.File
	file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_goTypes = nil
	file_github_com_spin_stack_spinbox_api_services_system_v1_info_proto_depIdxs = nil
}
