// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.1
// source: github.com/spin-stack/spinbox/api/types/spinbox/v1/options.proto

package spinbox

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SpinboxOpts specifies runtime options for the spinbox VM runtime.
// These options are passed from containerd to the shim when creating a task.
type SpinboxOpts struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// boot_cpus specifies the number of vCPUs to start the VM with.
	// If 0, uses the default from config or OCI spec limits.
	BootCpus uint32 `protobuf:"varint,1,opt,name=boot_cpus,json=bootCpus,proto3" json:"boot_cpus,omitempty"`
	// max_cpus specifies the maximum number of vCPUs that can be hot-plugged.
	// If 0, uses the default from config or OCI spec limits.
	MaxCpus uint32 `protobuf:"varint,2,opt,name=max_cpus,json=maxCpus,proto3" json:"max_cpus,omitempty"`
	// memory_mb specifies the initial memory size in megabytes.
	// If 0, uses the default from config or OCI spec limits.
	MemoryMb uint32 `protobuf:"varint,3,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	// max_memory_mb specifies the maximum memory that can be hot-plugged in megabytes.
	// If 0, uses the default from config or OCI spec limits.
	MaxMemoryMb uint32 `protobuf:"varint,4,opt,name=max_memory_mb,json=maxMemoryMb,proto3" json:"max_memory_mb,omitempty"`
	// io_uid specifies the I/O uid for the container.
	// This is passed through to runc inside the VM.
	IoUid uint32 `protobuf:"varint,7,opt,name=io_uid,json=ioUid,proto3" json:"io_uid,omitempty"`
	// io_gid specifies the I/O gid for the container.
	// This is passed through to runc inside the VM.
	IoGid         uint32 `protobuf:"varint,8,opt,name=io_gid,json=ioGid,proto3" json:"io_gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpinboxOpts) Reset() {
	*x = SpinboxOpts{}
	mi := &file_github_com_spin_stack_spinbox_api_types_spinbox_v1_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpinboxOpts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpinboxOpts) ProtoMessage() {}

func (x *SpinboxOpts) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_spin_stack_spinbox_api_types_spinbox_v1_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpinboxOpts.ProtoReflect.Descriptor instead.
func (*SpinboxOpts) Descriptor() ([]byte, []int) {
	return file_github_com_spin_stack_spinbox_api_types_spinbox_v1_options_proto_rawDescGZIP(), []int{0}
}

func (x *SpinboxOpts) GetBootCpus() uint32 {
	if x != nil {
		return x.BootCpus
	}
	return 0
}

func (x *SpinboxOpts) GetMaxCpus() uint32 {
	if x != nil {
		return x.MaxCpus
	}
	return 0
}

func (x *SpinboxOpts) GetMemoryMb() uint32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *SpinboxOpts) GetMaxMemoryMb() uint32 {
	if x != nil {
		return x.MaxMemoryMb
	}
	return 0
}

func (x *SpinboxOpts) GetIoUid() uint32 {
	if x != nil {
		return x.IoUid
	}
	return 0
}

func (x *SpinboxOpts) GetIoGid() uint32 {
	if x != nil {
		return x.IoGid
	}
	return 0
}

var File_github_com_spin_stack_spinbox_api_types_spinbox_v1_options_proto protoreflect.FileDescriptor

const file_github_com_spin_stack_spinbox_api_types_spinbox_v1_options_proto_rawDesc = "" +
	"\n" +
	"@github.com/spin-stack/spinbox/api/types/spinbox/v1/options.proto\x12\x18io.containerd.spinbox.v1\"\xb4\x01\n" +
	"\vSpinboxOpts\x12\x1b\n" +
	"\tboot_cpus\x18\x01 \x01(\rR\bbootCpus\x12\x19\n" +
	"\bmax_cpus\x18\x02 \x01(\rR\amaxCpus\x12\x1b\n" +
	"\tmemory_mb\x18\x03 \x01(\rR\bmemoryMb\x12\"\n" +
	"\rmax_memory_mb\x18\x04 \x01(\rR\vmaxMemoryMb\x12\x15\n" +
	"\x06io_uid\x18\a \x01(\rR\x05ioUid\x12\x15\n" +
	"\x06io_gid\x18\b \x01(\rR\x05ioGidB<Z:github.com/spin-stack/spinbox/api/types/spinbox/v1;spinboxb\x06proto3"

var (
	file_github_com_spin_stack_spinbox_api_types_spinbox_v1_options_proto_rawDescOnce sync.Once
	file_github_com_spin_stack_spinbox_api_types_spinbox_v1_options_proto_rawDescData []byte
)

func file_github_com_spin_stack_spinbox_api_types_spinbox_v1_options_proto_rawDescGZIP() []byte {
	file_github_com_spin_stack_spinbox_api_types_spinbox_v1_options_proto_rawDescOnce.Do(func() {
		file_github_com_spin_stack_spinbox_api_types_spinbox_v1_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_spin_stack_spinbox_api_types_spinbox_v1_options_proto_rawDesc), len(file_github_com_spin_stack_spinbox_api_types_spinbox_v1_options_proto_rawDesc)))
	})
	return file_github_com_spin_stack_spinbox_api_types_spinbox_v1_options_proto_rawDescData
}

var file_github_com_spin_stack_spinbox_api_types_spinbox_v1_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_spin_stack_spinbox_api_types_spinbox_v1_options_proto_goTypes = []any{
	(*SpinboxOpts)(nil), // 0: io.containerd.spinbox.v1.SpinboxOpts
}
var file_github_com_spin_stack_spinbox_api_types_spinbox_v1_options_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_spin_stack_spinbox_api_types_spinbox_v1_options_proto_init() }
func file_github_com_spin_stack_spinbox_api_types_spinbox_v1_options_proto_init() {
	if File_github_com_spin_stack_spinbox_api_types_spinbox_v1_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_spin_stack_spinbox_api_types_spinbox_v1_options_proto_rawDesc), len(file_github_com_spin_stack_spinbox_api_types_spinbox_v1_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_spin_stack_spinbox_api_types_spinbox_v1_options_proto_goTypes,
		DependencyIndexes: file_github_com_spin_stack_spinbox_api_types_spinbox_v1_options_proto_depIdxs,
		MessageInfos:      file_github_com_spin_stack_spinbox_api_types_spinbox_v1_options_proto_msgTypes,
	}.Build()
	File_github_com_spin_stack_spinbox_api_types_spinbox_v1_options_proto = out.File
	file_github_com_spin_stack_spinbox_api_types_spinbox_v1_options_proto_goTypes = nil
	file_github_com_spin_stack_spinbox_api_types_spinbox_v1_options_proto_depIdxs = nil
}
