// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.1
// source: github.com/spin-stack/spinbox/api/services/vmevents/v1/events.proto

package vmevents

import (
	types "github.com/containerd/containerd/api/types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_github_com_spin_stack_spinbox_api_services_vmevents_v1_events_proto protoreflect.FileDescriptor

const file_github_com_spin_stack_spinbox_api_services_vmevents_v1_events_proto_rawDesc = "" +
	"\n" +
	"Cgithub.com/spin-stack/spinbox/api/services/vmevents/v1/events.proto\x12\x1cspinbox.services.vmevents.v1\x1a6github.com/containerd/containerd/api/types/event.proto\x1a\x1bgoogle/protobuf/empty.proto2H\n" +
	"\x06Events\x12>\n" +
	"\x06Stream\x12\x16.google.protobuf.Empty\x1a\x1a.containerd.types.Envelope0\x01BAZ?github.com/spin-stack/spinbox/api/services/vmevents/v1;vmeventsb\x06proto3"

var file_github_com_spin_stack_spinbox_api_services_vmevents_v1_events_proto_goTypes = []any{
	(*emptypb.Empty)(nil),  // 0: google.protobuf.Empty
	(*types.Envelope)(nil), // 1: containerd.types.Envelope
}
var file_github_com_spin_stack_spinbox_api_services_vmevents_v1_events_proto_depIdxs = []int32{
	0, // 0: spinbox.services.vmevents.v1.Events.Stream:input_type -> google.protobuf.Empty
	1, // 1: spinbox.services.vmevents.v1.Events.Stream:output_type -> containerd.types.Envelope
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_github_com_spin_stack_spinbox_api_services_vmevents_v1_events_proto_init() }
func file_github_com_spin_stack_spinbox_api_services_vmevents_v1_events_proto_init() {
	if File_github_com_spin_stack_spinbox_api_services_vmevents_v1_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_spin_stack_spinbox_api_services_vmevents_v1_events_proto_rawDesc), len(file_github_com_spin_stack_spinbox_api_services_vmevents_v1_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_spin_stack_spinbox_api_services_vmevents_v1_events_proto_goTypes,
		DependencyIndexes: file_github_com_spin_stack_spinbox_api_services_vmevents_v1_events_proto_depIdxs,
	}.Build()
	File_github_com_spin_stack_spinbox_api_services_vmevents_v1_events_proto = out.File
	file_github_com_spin_stack_spinbox_api_services_vmevents_v1_events_proto_goTypes = nil
	file_github_com_spin_stack_spinbox_api_services_vmevents_v1_events_proto_depIdxs = nil
}
