// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.1
// source: github.com/spin-stack/spinbox/api/services/bundle/v1/bundle.proto

package bundle

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the unique identifier for the bundle to create.
	ID string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// files is a map of filename to file contents.
	// Keys must be simple filenames without path components (e.g., "config.json", "hosts", "resolv.conf").
	// Values are the file contents as raw bytes.
	//
	// SECURITY: The server validates all filenames to prevent attacks:
	//   - Empty filenames are rejected
	//   - Absolute paths (starting with /) are rejected
	//   - Path separators (/ or \) are rejected - only simple filenames allowed
	//   - "." and ".." are rejected
	//
	// Invalid filenames result in INVALID_ARGUMENT error.
	Files         map[string][]byte `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_github_com_spin_stack_spinbox_api_services_bundle_v1_bundle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_spin_stack_spinbox_api_services_bundle_v1_bundle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_github_com_spin_stack_spinbox_api_services_bundle_v1_bundle_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *CreateRequest) GetFiles() map[string][]byte {
	if x != nil {
		return x.Files
	}
	return nil
}

type CreateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// bundle is the absolute path to the created bundle directory on the VM filesystem.
	Bundle        string `protobuf:"bytes,1,opt,name=bundle,proto3" json:"bundle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_github_com_spin_stack_spinbox_api_services_bundle_v1_bundle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_spin_stack_spinbox_api_services_bundle_v1_bundle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_github_com_spin_stack_spinbox_api_services_bundle_v1_bundle_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResponse) GetBundle() string {
	if x != nil {
		return x.Bundle
	}
	return ""
}

var File_github_com_spin_stack_spinbox_api_services_bundle_v1_bundle_proto protoreflect.FileDescriptor

const file_github_com_spin_stack_spinbox_api_services_bundle_v1_bundle_proto_rawDesc = "" +
	"\n" +
	"Agithub.com/spin-stack/spinbox/api/services/bundle/v1/bundle.proto\x12%containerd.vminitd.services.bundle.v1\"\xb0\x01\n" +
	"\rCreateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12U\n" +
	"\x05files\x18\x02 \x03(\v2?.containerd.vminitd.services.bundle.v1.CreateRequest.FilesEntryR\x05files\x1a8\n" +
	"\n" +
	"FilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"(\n" +
	"\x0eCreateResponse\x12\x16\n" +
	"\x06bundle\x18\x01 \x01(\tR\x06bundle2\x7f\n" +
	"\x06Bundle\x12u\n" +
	"\x06Create\x124.containerd.vminitd.services.bundle.v1.CreateRequest\x1a5.containerd.vminitd.services.bundle.v1.CreateResponseB=Z;github.com/spin-stack/spinbox/api/services/bundle/v1;bundleb\x06proto3"

var (
	file_github_com_spin_stack_spinbox_api_services_bundle_v1_bundle_proto_rawDescOnce sync.Once
	file_github_com_spin_stack_spinbox_api_services_bundle_v1_bundle_proto_rawDescData []byte
)

func file_github_com_spin_stack_spinbox_api_services_bundle_v1_bundle_proto_rawDescGZIP() []byte {
	file_github_com_spin_stack_spinbox_api_services_bundle_v1_bundle_proto_rawDescOnce.Do(func() {
		file_github_com_spin_stack_spinbox_api_services_bundle_v1_bundle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_github_com_spin_stack_spinbox_api_services_bundle_v1_bundle_proto_rawDesc), len(file_github_com_spin_stack_spinbox_api_services_bundle_v1_bundle_proto_rawDesc)))
	})
	return file_github_com_spin_stack_spinbox_api_services_bundle_v1_bundle_proto_rawDescData
}

var file_github_com_spin_stack_spinbox_api_services_bundle_v1_bundle_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_github_com_spin_stack_spinbox_api_services_bundle_v1_bundle_proto_goTypes = []any{
	(*CreateRequest)(nil),  // 0: containerd.vminitd.services.bundle.v1.CreateRequest
	(*CreateResponse)(nil), // 1: containerd.vminitd.services.bundle.v1.CreateResponse
	nil,                    // 2: containerd.vminitd.services.bundle.v1.CreateRequest.FilesEntry
}
var file_github_com_spin_stack_spinbox_api_services_bundle_v1_bundle_proto_depIdxs = []int32{
	2, // 0: containerd.vminitd.services.bundle.v1.CreateRequest.files:type_name -> containerd.vminitd.services.bundle.v1.CreateRequest.FilesEntry
	0, // 1: containerd.vminitd.services.bundle.v1.Bundle.Create:input_type -> containerd.vminitd.services.bundle.v1.CreateRequest
	1, // 2: containerd.vminitd.services.bundle.v1.Bundle.Create:output_type -> containerd.vminitd.services.bundle.v1.CreateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_github_com_spin_stack_spinbox_api_services_bundle_v1_bundle_proto_init() }
func file_github_com_spin_stack_spinbox_api_services_bundle_v1_bundle_proto_init() {
	if File_github_com_spin_stack_spinbox_api_services_bundle_v1_bundle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_github_com_spin_stack_spinbox_api_services_bundle_v1_bundle_proto_rawDesc), len(file_github_com_spin_stack_spinbox_api_services_bundle_v1_bundle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_github_com_spin_stack_spinbox_api_services_bundle_v1_bundle_proto_goTypes,
		DependencyIndexes: file_github_com_spin_stack_spinbox_api_services_bundle_v1_bundle_proto_depIdxs,
		MessageInfos:      file_github_com_spin_stack_spinbox_api_services_bundle_v1_bundle_proto_msgTypes,
	}.Build()
	File_github_com_spin_stack_spinbox_api_services_bundle_v1_bundle_proto = out.File
	file_github_com_spin_stack_spinbox_api_services_bundle_v1_bundle_proto_goTypes = nil
	file_github_com_spin_stack_spinbox_api_services_bundle_v1_bundle_proto_depIdxs = nil
}
